var responsiveNav=function(a,b){var c=!!a.getComputedStyle;a.getComputedStyle||(a.getComputedStyle=function(a){this.el=a;this.getPropertyValue=function(b){var c=/(\-([a-z]){1})/g;"float"===b&&(b="styleFloat");c.test(b)&&(b=b.replace(c,function(a,b,c){return c.toUpperCase()}));return a.currentStyle[b]?a.currentStyle[b]:null};return this});var d,g,f,e=b.createElement("style"),h=!1,k=function(a,b,c,d){if("addEventListener"in a)try{a.addEventListener(b,c,d)}catch(m){if("object"===typeof c&&c.handleEvent)a.addEventListener(b,
function(a){c.handleEvent.call(c,a)},d);else throw m;}else"attachEvent"in a&&("object"===typeof c&&c.handleEvent?a.attachEvent("on"+b,function(){c.handleEvent.call(c)}):a.attachEvent("on"+b,c))},l=function(a,b,c,d){if("removeEventListener"in a)try{a.removeEventListener(b,c,d)}catch(m){if("object"===typeof c&&c.handleEvent)a.removeEventListener(b,function(a){c.handleEvent.call(c,a)},d);else throw m;}else"detachEvent"in a&&("object"===typeof c&&c.handleEvent?a.detachEvent("on"+b,function(){c.handleEvent.call(c)}):
a.detachEvent("on"+b,c))},n=function(a){if(1>a.children.length)throw Error("The Nav container has no containing elements");for(var b=[],c=0;c<a.children.length;c++)1===a.children[c].nodeType&&b.push(a.children[c]);return b},p=function(a,b){for(var c in b)a.setAttribute(c,b[c])},m=function(a,b){a.className+=" "+b;a.className=a.className.replace(/(^\s*)|(\s*$)/g,"")},s=function(a,b){a.className=a.className.replace(RegExp("(\\s|^)"+b+"(\\s|$)")," ").replace(/(^\s*)|(\s*$)/g,"")},t=function(a,c){var e;
this.options={animate:!0,transition:400,label:"Menu",insert:"after",customToggle:"",openPos:"relative",jsClass:"js",init:function(){},open:function(){},close:function(){}};for(e in c)this.options[e]=c[e];m(b.documentElement,this.options.jsClass);this.wrapperEl=a.replace("#","");if(b.getElementById(this.wrapperEl))this.wrapper=b.getElementById(this.wrapperEl);else throw Error("The nav element you are trying to select doesn't exist");this.wrapper.inner=n(this.wrapper);g=this.options;d=this.wrapper;
this._init(this)};t.prototype={destroy:function(){this._removeStyles();s(d,"closed");s(d,"opened");d.removeAttribute("style");d.removeAttribute("aria-hidden");r=d=null;l(a,"load",this,!1);l(a,"resize",this,!1);l(f,"mousedown",this,!1);l(f,"touchstart",this,!1);l(f,"touchend",this,!1);l(f,"keyup",this,!1);l(f,"click",this,!1);g.customToggle?f.removeAttribute("aria-hidden"):f.parentNode.removeChild(f)},toggle:function(){h?(s(d,"opened"),m(d,"closed"),p(d,{"aria-hidden":"true"}),g.animate?setTimeout(function(){d.style.position=
"absolute"},g.transition+10):d.style.position="absolute",h=!1,g.close()):(s(d,"closed"),m(d,"opened"),d.style.position=g.openPos,p(d,{"aria-hidden":"false"}),h=!0,g.open())},handleEvent:function(b){b=b||a.event;switch(b.type){case "mousedown":this._onmousedown(b);break;case "touchstart":this._ontouchstart(b);break;case "touchend":this._ontouchend(b);break;case "keyup":this._onkeyup(b);break;case "click":this._onclick(b);break;case "load":this._transitions(b);this._resize(b);break;case "resize":this._resize(b)}},
_init:function(){m(d,"closed");this._createToggle();k(a,"load",this,!1);k(a,"resize",this,!1);k(f,"mousedown",this,!1);k(f,"touchstart",this,!1);k(f,"touchend",this,!1);k(f,"keyup",this,!1);k(f,"click",this,!1)},_createStyles:function(){e.parentNode||b.getElementsByTagName("head")[0].appendChild(e)},_removeStyles:function(){e.parentNode&&e.parentNode.removeChild(e)},_createToggle:function(){if(g.customToggle){var a=g.customToggle.replace("#","");if(b.getElementById(a))f=b.getElementById(a);else throw Error("The custom nav toggle you are trying to select doesn't exist");
}else a=b.createElement("a"),a.innerHTML=g.label,p(a,{href:"#",id:"nav-toggle"}),"after"===g.insert?d.parentNode.insertBefore(a,d.nextSibling):d.parentNode.insertBefore(a,d),f=b.getElementById("nav-toggle")},_preventDefault:function(a){a.preventDefault?(a.preventDefault(),a.stopPropagation()):a.returnValue=!1},_onmousedown:function(b){var c=b||a.event;3!==c.which&&2!==c.button&&(this._preventDefault(b),this.toggle(b))},_ontouchstart:function(a){f.onmousedown=null;this._preventDefault(a);this.toggle(a)},
_ontouchend:function(){var a=this;d.addEventListener("click",a._preventDefault,!0);setTimeout(function(){d.removeEventListener("click",a._preventDefault,!0)},g.transition)},_onkeyup:function(b){13===(b||a.event).keyCode&&this.toggle(b)},_onclick:function(a){this._preventDefault(a)},_transitions:function(){if(g.animate){var a=d.style,b="max-height "+g.transition+"ms";a.WebkitTransition=b;a.MozTransition=b;a.OTransition=b;a.transition=b}},_calcHeight:function(){for(var a=0,b=0;b<d.inner.length;b++)a+=
d.inner[b].offsetHeight;a="#"+this.wrapperEl+".opened{max-height:"+a+"px}";c&&(e.innerHTML=a)},_resize:function(){"none"!==a.getComputedStyle(f,null).getPropertyValue("display")?(p(f,{"aria-hidden":"false"}),d.className.match(/(^|\s)closed(\s|$)/)&&(p(d,{"aria-hidden":"true"}),d.style.position="absolute"),this._createStyles(),this._calcHeight()):(p(f,{"aria-hidden":"true"}),p(d,{"aria-hidden":"false"}),d.style.position=g.openPos,this._removeStyles());g.init()}};var r;return function(a,b){r||(r=new t(a,
b));return r}}(window,document);if("undefined"==typeof YAHOO||!YAHOO)var YAHOO={};YAHOO.namespace=function(){var a=arguments,b=null,c,d,g;for(c=0;c<a.length;c+=1)for(g=a[c].split("."),b=YAHOO,d="YAHOO"==g[0]?1:0;d<g.length;d+=1)b[g[d]]=b[g[d]]||{},b=b[g[d]];return b};YAHOO.log=function(a,b,c){var d=YAHOO.widget.Logger;return d&&d.log?d.log(a,b,c):!1};
YAHOO.register=function(a,b,c){var d=YAHOO.env.modules;d[a]||(d[a]={versions:[],builds:[]});var d=d[a],g=c.version;c=c.build;var f=YAHOO.env.listeners;d.name=a;d.version=g;d.build=c;d.versions.push(g);d.builds.push(c);d.mainClass=b;for(var e=0;e<f.length;e+=1)f[e](d);b?(b.VERSION=g,b.BUILD=c):YAHOO.log("mainClass is undefined for module "+a,"warn")};YAHOO.env=YAHOO.env||{modules:[],listeners:[]};YAHOO.env.getVersion=function(a){return YAHOO.env.modules[a]||null};
YAHOO.env.ua=function(){var a={ie:0,opera:0,gecko:0,webkit:0,mobile:null,air:0},b=navigator.userAgent,c;/KHTML/.test(b)&&(a.webkit=1);if((c=b.match(/AppleWebKit\/([^\s]*)/))&&c[1]){a.webkit=parseFloat(c[1]);if(/ Mobile\//.test(b))a.mobile="Apple";else if(c=b.match(/NokiaN[^\/]*/))a.mobile=c[0];if(c=b.match(/AdobeAIR\/([^\s]*)/))a.air=c[0]}if(!a.webkit)if((c=b.match(/Opera[\s\/]([^\s]*)/))&&c[1]){if(a.opera=parseFloat(c[1]),c=b.match(/Opera Mini[^;]*/))a.mobile=c[0]}else if((c=b.match(/MSIE\s([^;]*)/))&&
c[1])a.ie=parseFloat(c[1]);else if(c=b.match(/Gecko\/([^\s]*)/))a.gecko=1,(c=b.match(/rv:([^\s\)]*)/))&&c[1]&&(a.gecko=parseFloat(c[1]));return a}();(function(){YAHOO.namespace("util","widget","example");if("undefined"!==typeof YAHOO_config){var a=YAHOO_config.listener,b=YAHOO.env.listeners,c=!0,d;if(a){for(d=0;d<b.length;d+=1)if(b[d]==a){c=!1;break}c&&b.push(a)}}})();YAHOO.lang=YAHOO.lang||{};
(function(){var a=YAHOO.lang,b=["toString","valueOf"],c={isArray:function(b){return b?a.isNumber(b.length)&&a.isFunction(b.splice):!1},isBoolean:function(a){return"boolean"===typeof a},isFunction:function(a){return"function"===typeof a},isNull:function(a){return null===a},isNumber:function(a){return"number"===typeof a&&isFinite(a)},isObject:function(b){return b&&("object"===typeof b||a.isFunction(b))||!1},isString:function(a){return"string"===typeof a},isUndefined:function(a){return"undefined"===
typeof a},_IEEnumFix:YAHOO.env.ua.ie?function(c,g){for(var f=0;f<b.length;f+=1){var e=b[f],h=g[e];a.isFunction(h)&&h!=Object.prototype[e]&&(c[e]=h)}}:function(){},extend:function(b,c,f){if(!c||!b)throw Error("extend failed, please check that all dependencies are included.");var e=function(){};e.prototype=c.prototype;b.prototype=new e;b.prototype.constructor=b;b.superclass=c.prototype;c.prototype.constructor==Object.prototype.constructor&&(c.prototype.constructor=c);if(f){for(var h in f)a.hasOwnProperty(f,
h)&&(b.prototype[h]=f[h]);a._IEEnumFix(b.prototype,f)}},augmentObject:function(b,c){if(!c||!b)throw Error("Absorb failed, verify dependencies.");var f=arguments,e,h=f[2];if(h&&!0!==h)for(e=2;e<f.length;e+=1)b[f[e]]=c[f[e]];else{for(e in c)!h&&e in b||(b[e]=c[e]);a._IEEnumFix(b,c)}},augmentProto:function(b,c){if(!c||!b)throw Error("Augment failed, verify dependencies.");for(var f=[b.prototype,c.prototype],e=2;e<arguments.length;e+=1)f.push(arguments[e]);a.augmentObject.apply(this,f)},dump:function(b,
c){var f,e,h=[];if(a.isObject(b)){if(b instanceof Date||"nodeType"in b&&"tagName"in b)return b;if(a.isFunction(b))return"f(){...}"}else return b+"";c=a.isNumber(c)?c:3;if(a.isArray(b)){h.push("[");f=0;for(e=b.length;f<e;f+=1)a.isObject(b[f])?h.push(0<c?a.dump(b[f],c-1):"{...}"):h.push(b[f]),h.push(", ");1<h.length&&h.pop();h.push("]")}else{h.push("{");for(f in b)a.hasOwnProperty(b,f)&&(h.push(f+" => "),a.isObject(b[f])?h.push(0<c?a.dump(b[f],c-1):"{...}"):h.push(b[f]),h.push(", "));1<h.length&&h.pop();
h.push("}")}return h.join("")},substitute:function(b,c,f){for(var e,h,k,l,n,p=[],m;;){e=b.lastIndexOf("{");if(0>e)break;h=b.indexOf("}",e);if(e+1>=h)break;l=m=b.substring(e+1,h);n=null;k=l.indexOf(" ");-1<k&&(n=l.substring(k+1),l=l.substring(0,k));k=c[l];f&&(k=f(l,k,n));a.isObject(k)?a.isArray(k)?k=a.dump(k,parseInt(n,10)):(n=n||"",l=n.indexOf("dump"),-1<l&&(n=n.substring(4)),k=k.toString===Object.prototype.toString||-1<l?a.dump(k,parseInt(n,10)):k.toString()):a.isString(k)||a.isNumber(k)||(k="~-"+
p.length+"-~",p[p.length]=m);b=b.substring(0,e)+k+b.substring(h+1)}for(e=p.length-1;0<=e;e-=1)b=b.replace(RegExp("~-"+e+"-~"),"{"+p[e]+"}","g");return b},trim:function(a){try{return a.replace(/^\s+|\s+$/g,"")}catch(b){return a}},merge:function(){for(var b={},c=arguments,f=0,e=c.length;f<e;f+=1)a.augmentObject(b,c[f],!0);return b},later:function(b,c,f,e,h){b=b||0;c=c||{};var k=f,l=e,n;a.isString(f)&&(k=c[f]);if(!k)throw new TypeError("method undefined");a.isArray(l)||(l=[e]);f=function(){k.apply(c,
l)};n=h?setInterval(f,b):setTimeout(f,b);return{interval:h,cancel:function(){this.interval?clearInterval(n):clearTimeout(n)}}},isValue:function(b){return a.isObject(b)||a.isString(b)||a.isNumber(b)||a.isBoolean(b)}};a.hasOwnProperty=Object.prototype.hasOwnProperty?function(a,b){return a&&a.hasOwnProperty(b)}:function(b,c){return!a.isUndefined(b[c])&&b.constructor.prototype[c]!==b[c]};c.augmentObject(a,c,!0);YAHOO.util.Lang=a;a.augment=a.augmentProto;YAHOO.augment=a.augmentProto;YAHOO.extend=a.extend})();
YAHOO.register("yahoo",YAHOO,{version:"2.6.0",build:"1321"});
(function(){var a=YAHOO.util,b=YAHOO.lang,c,d,g={},f={},e=window.document;YAHOO.env._id_counter=YAHOO.env._id_counter||0;var h=YAHOO.env.ua.opera,k=YAHOO.env.ua.webkit,l=YAHOO.env.ua.ie,n=/(-[a-z])/i,p=/^body|html$/i,m=function(a){if(!n.test(a))return a;if(g[a])return g[a];for(var b=a;n.exec(b);)b=b.replace(RegExp.$1,RegExp.$1.substr(1).toUpperCase());return g[a]=b},s=function(a){var b=f[a];b||(b=RegExp("(?:^|\\s+)"+a+"(?:\\s+|$)"),f[a]=b);return b};c=e.defaultView&&e.defaultView.getComputedStyle?
function(a,b){var c=null;"float"==b&&(b="cssFloat");var d=a.ownerDocument.defaultView.getComputedStyle(a,"");d&&(c=d[m(b)]);return a.style[b]||c}:e.documentElement.currentStyle&&l?function(a,b){switch(m(b)){case "opacity":var c=100;try{c=a.filters["DXImageTransform.Microsoft.Alpha"].opacity}catch(d){try{c=a.filters("alpha").opacity}catch(e){}}return c/100;case "float":b="styleFloat";default:return c=a.currentStyle?a.currentStyle[b]:null,a.style[b]||c}}:function(a,b){return a.style[b]};d=l?function(a,
c,d){switch(c){case "opacity":b.isString(a.style.filter)&&(a.style.filter="alpha(opacity="+100*d+")",a.currentStyle&&a.currentStyle.hasLayout||(a.style.zoom=1));break;case "float":c="styleFloat";default:a.style[c]=d}}:function(a,b,c){"float"==b&&(b="cssFloat");a.style[b]=c};var t=function(a,b){return a&&1==a.nodeType&&(!b||b(a))};YAHOO.util.Dom={get:function(b){if(b){if(b.nodeType||b.item)return b;if("string"===typeof b)return e.getElementById(b);if("length"in b){for(var c=[],d=0,m=b.length;d<m;++d)c[c.length]=
a.Dom.get(b[d]);return c}return b}return null},getStyle:function(b,d){d=m(d);return a.Dom.batch(b,function(a){return c(a,d)},a.Dom,!0)},setStyle:function(b,c,e){c=m(c);a.Dom.batch(b,function(a){d(a,c,e)},a.Dom,!0)},getXY:function(b){return a.Dom.batch(b,function(a){return null!==a.parentNode&&null!==a.offsetParent&&"none"!=this.getStyle(a,"display")||a==a.ownerDocument.body?r(a):!1},a.Dom,!0)},getX:function(b){return a.Dom.batch(b,function(b){return a.Dom.getXY(b)[0]},a.Dom,!0)},getY:function(b){return a.Dom.batch(b,
function(b){return a.Dom.getXY(b)[1]},a.Dom,!0)},setXY:function(b,c,d){a.Dom.batch(b,function(a){var b=this.getStyle(a,"position");"static"==b&&(this.setStyle(a,"position","relative"),b="relative");var m=this.getXY(a);if(!1===m)return!1;var q=[parseInt(this.getStyle(a,"left"),10),parseInt(this.getStyle(a,"top"),10)];isNaN(q[0])&&(q[0]="relative"==b?0:a.offsetLeft);isNaN(q[1])&&(q[1]="relative"==b?0:a.offsetTop);null!==c[0]&&(a.style.left=c[0]-m[0]+q[0]+"px");null!==c[1]&&(a.style.top=c[1]-m[1]+q[1]+
"px");d||(b=this.getXY(a),(null!==c[0]&&b[0]!=c[0]||null!==c[1]&&b[1]!=c[1])&&this.setXY(a,c,!0))},a.Dom,!0)},setX:function(b,c){a.Dom.setXY(b,[c,null])},setY:function(b,c){a.Dom.setXY(b,[null,c])},getRegion:function(b){return a.Dom.batch(b,function(b){return null!==b.parentNode&&null!==b.offsetParent&&"none"!=this.getStyle(b,"display")||b==b.ownerDocument.body?a.Region.getRegion(b):!1},a.Dom,!0)},getClientWidth:function(){return a.Dom.getViewportWidth()},getClientHeight:function(){return a.Dom.getViewportHeight()},
getElementsByClassName:function(c,d,m,f){c=b.trim(c);d=d||"*";m=m?a.Dom.get(m):e;if(!m)return[];var g=[];d=m.getElementsByTagName(d);c=s(c);m=0;for(var r=d.length;m<r;++m)c.test(d[m].className)&&(g[g.length]=d[m],f&&f.call(d[m],d[m]));return g},hasClass:function(b,c){var d=s(c);return a.Dom.batch(b,function(a){return d.test(a.className)},a.Dom,!0)},addClass:function(c,d){return a.Dom.batch(c,function(a){if(this.hasClass(a,d))return!1;a.className=b.trim([a.className,d].join(" "));return!0},a.Dom,!0)},
removeClass:function(c,d){var m=s(d);return a.Dom.batch(c,function(a){var c=!1,q=a.className;d&&(q&&this.hasClass(a,d))&&(a.className=q.replace(m," "),this.hasClass(a,d)&&this.removeClass(a,d),a.className=b.trim(a.className),""===a.className&&a.removeAttribute(a.hasAttribute?"class":"className"),c=!0);return c},a.Dom,!0)},replaceClass:function(c,d,m){if(!m||d===m)return!1;var e=s(d);return a.Dom.batch(c,function(a){if(!this.hasClass(a,d))return this.addClass(a,m),!0;a.className=a.className.replace(e,
" "+m+" ");this.hasClass(a,d)&&this.removeClass(a,d);a.className=b.trim(a.className);return!0},a.Dom,!0)},generateId:function(b,c){c=c||"yui-gen";var d=function(a){if(a&&a.id)return a.id;var b=c+YAHOO.env._id_counter++;a&&(a.id=b);return b};return a.Dom.batch(b,d,a.Dom,!0)||d.apply(a.Dom,arguments)},isAncestor:function(b,c){b=a.Dom.get(b);c=a.Dom.get(c);var d=!1;b&&c&&(b.nodeType&&c.nodeType)&&(b.contains&&b!==c?d=b.contains(c):b.compareDocumentPosition&&(d=!!(b.compareDocumentPosition(c)&16)));return d},
inDocument:function(a){return this.isAncestor(e.documentElement,a)},getElementsBy:function(b,c,d,m){c=c||"*";d=d?a.Dom.get(d):e;if(!d)return[];var f=[];c=d.getElementsByTagName(c);d=0;for(var s=c.length;d<s;++d)b(c[d])&&(f[f.length]=c[d],m&&m(c[d]));return f},batch:function(b,c,d,m){b=b&&(b.tagName||b.item)?b:a.Dom.get(b);if(!b||!c)return!1;m=m?d:window;if(b.tagName||void 0===b.length)return c.call(m,b,d);for(var e=[],f=0,s=b.length;f<s;++f)e[e.length]=c.call(m,b[f],d);return e},getDocumentHeight:function(){return Math.max("CSS1Compat"!=
e.compatMode?e.body.scrollHeight:e.documentElement.scrollHeight,a.Dom.getViewportHeight())},getDocumentWidth:function(){return Math.max("CSS1Compat"!=e.compatMode?e.body.scrollWidth:e.documentElement.scrollWidth,a.Dom.getViewportWidth())},getViewportHeight:function(){var a=self.innerHeight,b=e.compatMode;!b&&!l||h||(a="CSS1Compat"==b?e.documentElement.clientHeight:e.body.clientHeight);return a},getViewportWidth:function(){var a=self.innerWidth,b=e.compatMode;if(b||l)a="CSS1Compat"==b?e.documentElement.clientWidth:
e.body.clientWidth;return a},getAncestorBy:function(a,b){for(;a=a.parentNode;)if(t(a,b))return a;return null},getAncestorByClassName:function(b,c){return(b=a.Dom.get(b))?a.Dom.getAncestorBy(b,function(b){return a.Dom.hasClass(b,c)}):null},getAncestorByTagName:function(b,c){return(b=a.Dom.get(b))?a.Dom.getAncestorBy(b,function(a){return a.tagName&&a.tagName.toUpperCase()==c.toUpperCase()}):null},getPreviousSiblingBy:function(a,b){for(;a;)if(a=a.previousSibling,t(a,b))return a;return null},getPreviousSibling:function(b){return(b=
a.Dom.get(b))?a.Dom.getPreviousSiblingBy(b):null},getNextSiblingBy:function(a,b){for(;a;)if(a=a.nextSibling,t(a,b))return a;return null},getNextSibling:function(b){return(b=a.Dom.get(b))?a.Dom.getNextSiblingBy(b):null},getFirstChildBy:function(b,c){return(t(b.firstChild,c)?b.firstChild:null)||a.Dom.getNextSiblingBy(b.firstChild,c)},getFirstChild:function(b,c){return(b=a.Dom.get(b))?a.Dom.getFirstChildBy(b):null},getLastChildBy:function(b,c){return b?(t(b.lastChild,c)?b.lastChild:null)||a.Dom.getPreviousSiblingBy(b.lastChild,
c):null},getLastChild:function(b){b=a.Dom.get(b);return a.Dom.getLastChildBy(b)},getChildrenBy:function(b,c){var d=a.Dom.getFirstChildBy(b,c),m=d?[d]:[];a.Dom.getNextSiblingBy(d,function(a){if(!c||c(a))m[m.length]=a;return!1});return m},getChildren:function(b){b=a.Dom.get(b);return a.Dom.getChildrenBy(b)},getDocumentScrollLeft:function(a){a=a||e;return Math.max(a.documentElement.scrollLeft,a.body.scrollLeft)},getDocumentScrollTop:function(a){a=a||e;return Math.max(a.documentElement.scrollTop,a.body.scrollTop)},
insertBefore:function(b,c){b=a.Dom.get(b);c=a.Dom.get(c);return b&&c&&c.parentNode?c.parentNode.insertBefore(b,c):null},insertAfter:function(b,c){b=a.Dom.get(b);c=a.Dom.get(c);return b&&c&&c.parentNode?c.nextSibling?c.parentNode.insertBefore(b,c.nextSibling):c.parentNode.appendChild(b):null},getClientRegion:function(){var b=a.Dom.getDocumentScrollTop(),c=a.Dom.getDocumentScrollLeft(),d=a.Dom.getViewportWidth()+c,m=a.Dom.getViewportHeight()+b;return new a.Region(b,d,m,c)}};var r=function(){return e.documentElement.getBoundingClientRect?
function(b){var c=b.getBoundingClientRect(),d=Math.round;b=b.ownerDocument;return[d(c.left+a.Dom.getDocumentScrollLeft(b)),d(c.top+a.Dom.getDocumentScrollTop(b))]}:function(b){var c=[b.offsetLeft,b.offsetTop],d=b.offsetParent,m=k&&"absolute"==a.Dom.getStyle(b,"position")&&b.offsetParent==b.ownerDocument.body;if(d!=b)for(;d;)c[0]+=d.offsetLeft,c[1]+=d.offsetTop,!m&&(k&&"absolute"==a.Dom.getStyle(d,"position"))&&(m=!0),d=d.offsetParent;m&&(c[0]-=b.ownerDocument.body.offsetLeft,c[1]-=b.ownerDocument.body.offsetTop);
for(d=b.parentNode;d.tagName&&!p.test(d.tagName);){if(d.scrollTop||d.scrollLeft)c[0]-=d.scrollLeft,c[1]-=d.scrollTop;d=d.parentNode}return c}}()})();YAHOO.util.Region=function(a,b,c,d){this.top=a;this[1]=a;this.right=b;this.bottom=c;this.left=d;this[0]=d};YAHOO.util.Region.prototype.contains=function(a){return a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom};YAHOO.util.Region.prototype.getArea=function(){return(this.bottom-this.top)*(this.right-this.left)};
YAHOO.util.Region.prototype.intersect=function(a){var b=Math.max(this.top,a.top),c=Math.min(this.right,a.right),d=Math.min(this.bottom,a.bottom);a=Math.max(this.left,a.left);return d>=b&&c>=a?new YAHOO.util.Region(b,c,d,a):null};YAHOO.util.Region.prototype.union=function(a){var b=Math.min(this.top,a.top),c=Math.max(this.right,a.right),d=Math.max(this.bottom,a.bottom);a=Math.min(this.left,a.left);return new YAHOO.util.Region(b,c,d,a)};
YAHOO.util.Region.prototype.toString=function(){return"Region {top: "+this.top+", right: "+this.right+", bottom: "+this.bottom+", left: "+this.left+"}"};YAHOO.util.Region.getRegion=function(a){var b=YAHOO.util.Dom.getXY(a);return new YAHOO.util.Region(b[1],b[0]+a.offsetWidth,b[1]+a.offsetHeight,b[0])};YAHOO.util.Point=function(a,b){YAHOO.lang.isArray(a)&&(b=a[1],a=a[0]);this.x=this.right=this.left=this[0]=a;this.y=this.top=this.bottom=this[1]=b};YAHOO.util.Point.prototype=new YAHOO.util.Region;
YAHOO.register("dom",YAHOO.util.Dom,{version:"2.6.0",build:"1321"});YAHOO.util.CustomEvent=function(a,b,c,d){this.type=a;this.scope=b||window;this.silent=c;this.signature=d||YAHOO.util.CustomEvent.LIST;this.subscribers=[];"_YUICEOnSubscribe"!==a&&(this.subscribeEvent=new YAHOO.util.CustomEvent("_YUICEOnSubscribe",this,!0));this.lastError=null};YAHOO.util.CustomEvent.LIST=0;YAHOO.util.CustomEvent.FLAT=1;
YAHOO.util.CustomEvent.prototype={subscribe:function(a,b,c){if(!a)throw Error("Invalid callback for subscriber to '"+this.type+"'");this.subscribeEvent&&this.subscribeEvent.fire(a,b,c);this.subscribers.push(new YAHOO.util.Subscriber(a,b,c))},unsubscribe:function(a,b){if(!a)return this.unsubscribeAll();for(var c=!1,d=0,g=this.subscribers.length;d<g;++d){var f=this.subscribers[d];f&&f.contains(a,b)&&(this._delete(d),c=!0)}return c},fire:function(){this.lastError=null;var a=this.subscribers.length;if(!a&&
this.silent)return!0;var b=[].slice.call(arguments,0),c=!0,d,g=this.subscribers.slice(),f=YAHOO.util.Event.throwErrors;for(d=0;d<a;++d){var e=g[d];if(e){var h=e.getScope(this.scope);if(this.signature==YAHOO.util.CustomEvent.FLAT){var k=null;0<b.length&&(k=b[0]);try{c=e.fn.call(h,k,e.obj)}catch(l){if(this.lastError=l,f)throw l;}}else try{c=e.fn.call(h,this.type,b,e.obj)}catch(n){if(this.lastError=n,f)throw n;}if(!1===c)break}}return!1!==c},unsubscribeAll:function(){for(var a=this.subscribers.length-
1;-1<a;a--)this._delete(a);this.subscribers=[];return a},_delete:function(a){var b=this.subscribers[a];b&&(delete b.fn,delete b.obj);this.subscribers.splice(a,1)},toString:function(){return"CustomEvent: '"+this.type+"', scope: "+this.scope}};YAHOO.util.Subscriber=function(a,b,c){this.fn=a;this.obj=YAHOO.lang.isUndefined(b)?null:b;this.override=c};YAHOO.util.Subscriber.prototype.getScope=function(a){return this.override?!0===this.override?this.obj:this.override:a};
YAHOO.util.Subscriber.prototype.contains=function(a,b){return b?this.fn==a&&this.obj==b:this.fn==a};YAHOO.util.Subscriber.prototype.toString=function(){return"Subscriber { obj: "+this.obj+", override: "+(this.override||"no")+" }"};
YAHOO.util.Event||(YAHOO.util.Event=function(){var a=!1,b=[],c=[],d=[],g=[],f=0,e=[],h=[],k=0,l={63232:38,63233:40,63234:37,63235:39,63276:33,63277:34,25:9},n=YAHOO.env.ua.ie?"focusin":"focus",p=YAHOO.env.ua.ie?"focusout":"blur";return{POLL_RETRYS:2E3,POLL_INTERVAL:20,EL:0,TYPE:1,FN:2,WFN:3,UNLOAD_OBJ:3,ADJ_SCOPE:4,OBJ:5,OVERRIDE:6,CAPTURE:7,lastError:null,isSafari:YAHOO.env.ua.webkit,webkit:YAHOO.env.ua.webkit,isIE:YAHOO.env.ua.ie,_interval:null,_dri:null,DOMReady:!1,throwErrors:!1,startInterval:function(){if(!this._interval){var a=
this;this._interval=setInterval(function(){a._tryPreloadAttach()},this.POLL_INTERVAL)}},onAvailable:function(a,b,c,d,g){a=YAHOO.lang.isString(a)?[a]:a;for(var h=0;h<a.length;h+=1)e.push({id:a[h],fn:b,obj:c,override:d,checkReady:g});f=this.POLL_RETRYS;this.startInterval()},onContentReady:function(a,b,c,d){this.onAvailable(a,b,c,d,!0)},onDOMReady:function(a,b,c){this.DOMReady?setTimeout(function(){var d=window;c&&(d=!0===c?b:c);a.call(d,"DOMReady",[],b)},0):this.DOMReadyEvent.subscribe(a,b,c)},_addListener:function(a,
e,f,r,q,v){if(!f||!f.call)return!1;if(this._isValidCollection(a)){for(var k=!0,l=0,n=a.length;l<n;++l)k=this._addListener(a[l],e,f,r,q,v)&&k;return k}if(YAHOO.lang.isString(a))if(k=this.getEl(a))a=k;else return this.onAvailable(a,function(){YAHOO.util.Event._addListener(a,e,f,r,q,v)}),!0;if(!a)return!1;if("unload"==e&&r!==this)return c[c.length]=[a,e,f,r,q,v],!0;var p=a;q&&(p=!0===q?r:q);k=function(b){return f.call(p,YAHOO.util.Event.getEvent(b,a),r)};l=[a,e,f,k,p,r,q,v];b[b.length]=l;if(this.useLegacyEvent(a,
e)){var u=this.getLegacyIndex(a,e);if(-1==u||a!=d[u][0])u=d.length,h[a.id+e]=u,d[u]=[a,e,a["on"+e]],g[u]=[],a["on"+e]=function(a){YAHOO.util.Event.fireLegacyEvent(YAHOO.util.Event.getEvent(a),u)};g[u].push(l)}else try{this._simpleAdd(a,e,k,v)}catch(w){return this.lastError=w,this._removeListener(a,e,f,v),!1}return!0},addListener:function(a,b,c,d,e){return this._addListener(a,b,c,d,e,!1)},addFocusListener:function(a,b,c,d){return this._addListener(a,n,b,c,d,!0)},removeFocusListener:function(a,b){return this._removeListener(a,
n,b,!0)},addBlurListener:function(a,b,c,d){return this._addListener(a,p,b,c,d,!0)},removeBlurListener:function(a,b){return this._removeListener(a,p,b,!0)},fireLegacyEvent:function(a,b){var c=!0,e,f,h;e=g[b].slice();for(var k=0,l=e.length;k<l;++k)(f=e[k])&&f[this.WFN]&&(h=f[this.ADJ_SCOPE],f=f[this.WFN].call(h,a),c=c&&f);if((e=d[b])&&e[2])e[2](a);return c},getLegacyIndex:function(a,b){var c=this.generateId(a)+b;return"undefined"==typeof h[c]?-1:h[c]},useLegacyEvent:function(a,b){return this.webkit&&
419>this.webkit&&("click"==b||"dblclick"==b)},_removeListener:function(a,d,e,f,h){var k,l;if("string"==typeof a)a=this.getEl(a);else if(this._isValidCollection(a)){h=!0;for(k=a.length-1;-1<k;k--)h=this._removeListener(a[k],d,e,f)&&h;return h}if(!e||!e.call)return this.purgeElement(a,!1,d);if("unload"==d){for(k=c.length-1;-1<k;k--)if((l=c[k])&&l[0]==a&&l[1]==d&&l[2]==e)return c.splice(k,1),!0;return!1}k=null;"undefined"===typeof h&&(h=this._getCacheIndex(a,d,e));0<=h&&(k=b[h]);if(!a||!k)return!1;if(this.useLegacyEvent(a,
d)){k=this.getLegacyIndex(a,d);var n=g[k];if(n)for(k=0,f=n.length;k<f;++k)if((l=n[k])&&l[this.EL]==a&&l[this.TYPE]==d&&l[this.FN]==e){n.splice(k,1);break}}else try{this._simpleRemove(a,d,k[this.WFN],f)}catch(p){return this.lastError=p,!1}delete b[h][this.WFN];delete b[h][this.FN];b.splice(h,1);return!0},removeListener:function(a,b,c){return this._removeListener(a,b,c,!1)},getTarget:function(a,b){return this.resolveTextNode(a.target||a.srcElement)},resolveTextNode:function(a){try{if(a&&3==a.nodeType)return a.parentNode}catch(b){}return a},
getPageX:function(a){var b=a.pageX;b||0===b||(b=a.clientX||0,this.isIE&&(b+=this._getScrollLeft()));return b},getPageY:function(a){var b=a.pageY;b||0===b||(b=a.clientY||0,this.isIE&&(b+=this._getScrollTop()));return b},getXY:function(a){return[this.getPageX(a),this.getPageY(a)]},getRelatedTarget:function(a){var b=a.relatedTarget;b||("mouseout"==a.type?b=a.toElement:"mouseover"==a.type&&(b=a.fromElement));return this.resolveTextNode(b)},getTime:function(a){if(!a.time){var b=(new Date).getTime();try{a.time=
b}catch(c){return this.lastError=c,b}}return a.time},stopEvent:function(a){this.stopPropagation(a);this.preventDefault(a)},stopPropagation:function(a){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0},preventDefault:function(a){a.preventDefault?a.preventDefault():a.returnValue=!1},getEvent:function(a,b){var c=a||window.event;if(!c)for(var d=this.getEvent.caller;d&&(!(c=d.arguments[0])||Event!=c.constructor);)d=d.caller;return c},getCharCode:function(a){a=a.keyCode||a.charCode||0;YAHOO.env.ua.webkit&&
a in l&&(a=l[a]);return a},_getCacheIndex:function(a,c,d){for(var e=0,f=b.length;e<f;e+=1){var g=b[e];if(g&&g[this.FN]==d&&g[this.EL]==a&&g[this.TYPE]==c)return e}return-1},generateId:function(a){var b=a.id;b||(b="yuievtautoid-"+k,++k,a.id=b);return b},_isValidCollection:function(a){try{return a&&"string"!==typeof a&&a.length&&!a.tagName&&!a.alert&&"undefined"!==typeof a[0]}catch(b){return!1}},elCache:{},getEl:function(a){return"string"===typeof a?document.getElementById(a):a},clearCache:function(){},
DOMReadyEvent:new YAHOO.util.CustomEvent("DOMReady",this),_load:function(b){a||(a=!0,b=YAHOO.util.Event,b._ready(),b._tryPreloadAttach())},_ready:function(a){a=YAHOO.util.Event;a.DOMReady||(a.DOMReady=!0,a.DOMReadyEvent.fire(),a._simpleRemove(document,"DOMContentLoaded",a._ready))},_tryPreloadAttach:function(){if(0===e.length)f=0,clearInterval(this._interval),this._interval=null;else if(!this.locked)if(this.isIE&&!this.DOMReady)this.startInterval();else{this.locked=!0;var b=!a;b||(b=0<f&&0<e.length);
var c=[],d=function(a,b){var c=a;b.override&&(c=!0===b.override?b.obj:b.override);b.fn.call(c,b.obj)},g,k,h,l,n=[];g=0;for(k=e.length;g<k;g+=1)if(h=e[g])if(l=this.getEl(h.id))if(h.checkReady){if(a||l.nextSibling||!b)n.push(h),e[g]=null}else d(l,h),e[g]=null;else c.push(h);g=0;for(k=n.length;g<k;g+=1)h=n[g],d(this.getEl(h.id),h);f--;if(b){for(g=e.length-1;-1<g;g--)(h=e[g])&&h.id||e.splice(g,1);this.startInterval()}else clearInterval(this._interval),this._interval=null;this.locked=!1}},purgeElement:function(a,
b,c){a=YAHOO.lang.isString(a)?this.getEl(a):a;var d=this.getListeners(a,c),e;if(d)for(e=d.length-1;-1<e;e--){var f=d[e];this._removeListener(a,f.type,f.fn,f.capture)}if(b&&a&&a.childNodes)for(e=0,d=a.childNodes.length;e<d;++e)this.purgeElement(a.childNodes[e],b,c)},getListeners:function(a,d){var e=[],f;f=d?"unload"===d?[c]:[b]:[b,c];for(var g=YAHOO.lang.isString(a)?this.getEl(a):a,h=0;h<f.length;h+=1){var k=f[h];if(k)for(var l=0,n=k.length;l<n;++l){var p=k[l];!p||(p[this.EL]!==g||d&&d!==p[this.TYPE])||
e.push({type:p[this.TYPE],fn:p[this.FN],obj:p[this.OBJ],adjust:p[this.OVERRIDE],scope:p[this.ADJ_SCOPE],capture:p[this.CAPTURE],index:l})}}return e.length?e:null},_unload:function(a){var e=YAHOO.util.Event,f,g,h,k=c.slice();f=0;for(h=c.length;f<h;++f)if(g=k[f]){var l=window;g[e.ADJ_SCOPE]&&(l=!0===g[e.ADJ_SCOPE]?g[e.UNLOAD_OBJ]:g[e.ADJ_SCOPE]);g[e.FN].call(l,e.getEvent(a,g[e.EL]),g[e.UNLOAD_OBJ]);k[f]=null}c=null;if(b)for(a=b.length-1;-1<a;a--)(g=b[a])&&e._removeListener(g[e.EL],g[e.TYPE],g[e.FN],
g[e.CAPTURE],a);d=null;e._simpleRemove(window,"unload",e._unload)},_getScrollLeft:function(){return this._getScroll()[1]},_getScrollTop:function(){return this._getScroll()[0]},_getScroll:function(){var a=document.documentElement,b=document.body;return a&&(a.scrollTop||a.scrollLeft)?[a.scrollTop,a.scrollLeft]:b?[b.scrollTop,b.scrollLeft]:[0,0]},regCE:function(){},_simpleAdd:function(){return window.addEventListener?function(a,b,c,d){a.addEventListener(b,c,d)}:window.attachEvent?function(a,b,c,d){a.attachEvent("on"+
b,c)}:function(){}}(),_simpleRemove:function(){return window.removeEventListener?function(a,b,c,d){a.removeEventListener(b,c,d)}:window.detachEvent?function(a,b,c){a.detachEvent("on"+b,c)}:function(){}}()}}(),function(){var a=YAHOO.util.Event;a.on=a.addListener;a.onFocus=a.addFocusListener;a.onBlur=a.addBlurListener;if(a.isIE){YAHOO.util.Event.onDOMReady(YAHOO.util.Event._tryPreloadAttach,YAHOO.util.Event,!0);var b=document.createElement("p");a._dri=setInterval(function(){try{b.doScroll("left"),clearInterval(a._dri),
a._dri=null,a._ready(),b=null}catch(c){}},a.POLL_INTERVAL)}else a.webkit&&525>a.webkit?a._dri=setInterval(function(){var b=document.readyState;if("loaded"==b||"complete"==b)clearInterval(a._dri),a._dri=null,a._ready()},a.POLL_INTERVAL):a._simpleAdd(document,"DOMContentLoaded",a._ready);a._simpleAdd(window,"load",a._load);a._simpleAdd(window,"unload",a._unload);a._tryPreloadAttach()}());YAHOO.util.EventProvider=function(){};
YAHOO.util.EventProvider.prototype={__yui_events:null,__yui_subscribers:null,subscribe:function(a,b,c,d){this.__yui_events=this.__yui_events||{};var g=this.__yui_events[a];g?g.subscribe(b,c,d):(g=this.__yui_subscribers=this.__yui_subscribers||{},g[a]||(g[a]=[]),g[a].push({fn:b,obj:c,override:d}))},unsubscribe:function(a,b,c){var d=this.__yui_events=this.__yui_events||{};if(a){if(d=d[a])return d.unsubscribe(b,c)}else{a=!0;for(var g in d)YAHOO.lang.hasOwnProperty(d,g)&&(a=a&&d[g].unsubscribe(b,c));
return a}return!1},unsubscribeAll:function(a){return this.unsubscribe(a)},createEvent:function(a,b){this.__yui_events=this.__yui_events||{};var c=b||{},d=this.__yui_events;if(!d[a]){var g=new YAHOO.util.CustomEvent(a,c.scope||this,c.silent,YAHOO.util.CustomEvent.FLAT);d[a]=g;c.onSubscribeCallback&&g.subscribeEvent.subscribe(c.onSubscribeCallback);this.__yui_subscribers=this.__yui_subscribers||{};if(c=this.__yui_subscribers[a])for(var f=0;f<c.length;++f)g.subscribe(c[f].fn,c[f].obj,c[f].override)}return d[a]},
fireEvent:function(a,b,c,d){this.__yui_events=this.__yui_events||{};var g=this.__yui_events[a];if(!g)return null;for(var f=[],e=1;e<arguments.length;++e)f.push(arguments[e]);return g.fire.apply(g,f)},hasEvent:function(a){return this.__yui_events&&this.__yui_events[a]?!0:!1}};
YAHOO.util.KeyListener=function(a,b,c,d){function g(a,c){b.shift||(b.shift=!1);b.alt||(b.alt=!1);b.ctrl||(b.ctrl=!1);if(a.shiftKey==b.shift&&a.altKey==b.alt&&a.ctrlKey==b.ctrl){var d;if(b.keys instanceof Array)for(var g=0;g<b.keys.length;g++)if(d=b.keys[g],d==a.charCode){f.fire(a.charCode,a);break}else{if(d==a.keyCode){f.fire(a.keyCode,a);break}}else d=b.keys,d==a.charCode?f.fire(a.charCode,a):d==a.keyCode&&f.fire(a.keyCode,a)}}d||(d=YAHOO.util.KeyListener.KEYDOWN);var f=new YAHOO.util.CustomEvent("keyPressed");
this.enabledEvent=new YAHOO.util.CustomEvent("enabled");this.disabledEvent=new YAHOO.util.CustomEvent("disabled");"string"==typeof a&&(a=document.getElementById(a));"function"==typeof c?f.subscribe(c):f.subscribe(c.fn,c.scope,c.correctScope);this.enable=function(){this.enabled||(YAHOO.util.Event.addListener(a,d,g),this.enabledEvent.fire(b));this.enabled=!0};this.disable=function(){this.enabled&&(YAHOO.util.Event.removeListener(a,d,g),this.disabledEvent.fire(b));this.enabled=!1};this.toString=function(){return"KeyListener ["+
b.keys+"] "+a.tagName+(a.id?"["+a.id+"]":"")}};YAHOO.util.KeyListener.KEYDOWN="keydown";YAHOO.util.KeyListener.KEYUP="keyup";YAHOO.util.KeyListener.KEY={ALT:18,BACK_SPACE:8,CAPS_LOCK:20,CONTROL:17,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,LEFT:37,META:224,NUM_LOCK:144,PAGE_DOWN:34,PAGE_UP:33,PAUSE:19,PRINTSCREEN:44,RIGHT:39,SCROLL_LOCK:145,SHIFT:16,SPACE:32,TAB:9,UP:38};YAHOO.register("event",YAHOO.util.Event,{version:"2.6.0",build:"1321"});
YAHOO.register("yahoo-dom-event",YAHOO,{version:"2.6.0",build:"1321"});YAHOO.util.Connect={_msxml_progid:["Microsoft.XMLHTTP","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP"],_http_headers:{},_has_http_headers:!1,_use_default_post_header:!0,_default_post_header:"application/x-www-form-urlencoded; charset=UTF-8",_default_form_header:"application/x-www-form-urlencoded",_use_default_xhr_header:!0,_default_xhr_header:"XMLHttpRequest",_has_default_headers:!0,_default_headers:{},_isFormSubmit:!1,_isFileUpload:!1,_formNode:null,_sFormData:null,_poll:{},_timeOut:{},_polling_interval:50,
_transaction_id:0,_submitElementValue:null,_hasSubmitListener:function(){return YAHOO.util.Event?(YAHOO.util.Event.addListener(document,"click",function(a){a=YAHOO.util.Event.getTarget(a);"input"==a.nodeName.toLowerCase()&&(a.type&&"submit"==a.type.toLowerCase())&&(YAHOO.util.Connect._submitElementValue=encodeURIComponent(a.name)+"="+encodeURIComponent(a.value))}),!0):!1}(),startEvent:new YAHOO.util.CustomEvent("start"),completeEvent:new YAHOO.util.CustomEvent("complete"),successEvent:new YAHOO.util.CustomEvent("success"),
failureEvent:new YAHOO.util.CustomEvent("failure"),uploadEvent:new YAHOO.util.CustomEvent("upload"),abortEvent:new YAHOO.util.CustomEvent("abort"),_customEvents:{onStart:["startEvent","start"],onComplete:["completeEvent","complete"],onSuccess:["successEvent","success"],onFailure:["failureEvent","failure"],onUpload:["uploadEvent","upload"],onAbort:["abortEvent","abort"]},setProgId:function(a){this._msxml_progid.unshift(a)},setDefaultPostHeader:function(a){"string"==typeof a?this._default_post_header=
a:"boolean"==typeof a&&(this._use_default_post_header=a)},setDefaultXhrHeader:function(a){"string"==typeof a?this._default_xhr_header=a:this._use_default_xhr_header=a},setPollingInterval:function(a){"number"==typeof a&&isFinite(a)&&(this._polling_interval=a)},createXhrObject:function(a){var b,c;try{c=new XMLHttpRequest,b={conn:c,tId:a}}catch(d){for(var g=0;g<this._msxml_progid.length;++g)try{c=new ActiveXObject(this._msxml_progid[g]);b={conn:c,tId:a};break}catch(f){}}finally{return b}},getConnectionObject:function(a){var b,
c=this._transaction_id;try{a?(b={},b.tId=c,b.isUpload=!0):b=this.createXhrObject(c),b&&this._transaction_id++}catch(d){}finally{return b}},asyncRequest:function(a,b,c,d){var g=this._isFileUpload?this.getConnectionObject(!0):this.getConnectionObject(),f=c&&c.argument?c.argument:null;if(g){c&&c.customevents&&this.initCustomEvents(g,c);if(this._isFormSubmit){if(this._isFileUpload)return this.uploadFile(g,c,b,d),g;"GET"==a.toUpperCase()?0!==this._sFormData.length&&(b+=(-1==b.indexOf("?")?"?":"&")+this._sFormData):
"POST"==a.toUpperCase()&&(d=d?this._sFormData+"&"+d:this._sFormData)}"GET"==a.toUpperCase()&&(c&&!1===c.cache)&&(b+=(-1==b.indexOf("?")?"?":"&")+"rnd="+(new Date).valueOf().toString());g.conn.open(a,b,!0);this._use_default_xhr_header&&(this._default_headers["X-Requested-With"]||this.initHeader("X-Requested-With",this._default_xhr_header,!0));"POST"===a.toUpperCase()&&this._use_default_post_header&&!1===this._isFormSubmit&&this.initHeader("Content-Type",this._default_post_header);(this._has_default_headers||
this._has_http_headers)&&this.setHeader(g);this.handleReadyState(g,c);g.conn.send(d||"");!0===this._isFormSubmit&&this.resetFormState();this.startEvent.fire(g,f);g.startEvent&&g.startEvent.fire(g,f);return g}return null},initCustomEvents:function(a,b){for(var c in b.customevents)this._customEvents[c][0]&&(a[this._customEvents[c][0]]=new YAHOO.util.CustomEvent(this._customEvents[c][1],b.scope?b.scope:null),a[this._customEvents[c][0]].subscribe(b.customevents[c]))},handleReadyState:function(a,b){var c=
this,d=b&&b.argument?b.argument:null;b&&b.timeout&&(this._timeOut[a.tId]=window.setTimeout(function(){c.abort(a,b,!0)},b.timeout));this._poll[a.tId]=window.setInterval(function(){a.conn&&4===a.conn.readyState&&(window.clearInterval(c._poll[a.tId]),delete c._poll[a.tId],b&&b.timeout&&(window.clearTimeout(c._timeOut[a.tId]),delete c._timeOut[a.tId]),c.completeEvent.fire(a,d),a.completeEvent&&a.completeEvent.fire(a,d),c.handleTransactionResponse(a,b))},this._polling_interval)},handleTransactionResponse:function(a,
b,c){var d,g=b&&b.argument?b.argument:null;try{d=void 0!==a.conn.status&&0!==a.conn.status?a.conn.status:13030}catch(f){d=13030}if(200<=d&&300>d||1223===d)c=this.createResponseObject(a,g),b&&b.success&&(b.scope?b.success.apply(b.scope,[c]):b.success(c)),this.successEvent.fire(c),a.successEvent&&a.successEvent.fire(c);else{switch(d){case 12002:case 12029:case 12030:case 12031:case 12152:case 13030:c=this.createExceptionObject(a.tId,g,c?c:!1);b&&b.failure&&(b.scope?b.failure.apply(b.scope,[c]):b.failure(c));
break;default:c=this.createResponseObject(a,g),b&&b.failure&&(b.scope?b.failure.apply(b.scope,[c]):b.failure(c))}this.failureEvent.fire(c);a.failureEvent&&a.failureEvent.fire(c)}this.releaseObject(a)},createResponseObject:function(a,b){var c={},d={};try{for(var g=a.conn.getAllResponseHeaders(),f=g.split("\n"),e=0;e<f.length;e++){var h=f[e].indexOf(":");-1!=h&&(d[f[e].substring(0,h)]=f[e].substring(h+2))}}catch(k){}c.tId=a.tId;c.status=1223==a.conn.status?204:a.conn.status;c.statusText=1223==a.conn.status?
"No Content":a.conn.statusText;c.getResponseHeader=d;c.getAllResponseHeaders=g;c.responseText=a.conn.responseText;c.responseXML=a.conn.responseXML;b&&(c.argument=b);return c},createExceptionObject:function(a,b,c){var d={};d.tId=a;c?(d.status=-1,d.statusText="transaction aborted"):(d.status=0,d.statusText="communication failure");b&&(d.argument=b);return d},initHeader:function(a,b,c){(c?this._default_headers:this._http_headers)[a]=b;c?this._has_default_headers=!0:this._has_http_headers=!0},setHeader:function(a){var b;
if(this._has_default_headers)for(b in this._default_headers)YAHOO.lang.hasOwnProperty(this._default_headers,b)&&a.conn.setRequestHeader(b,this._default_headers[b]);if(this._has_http_headers){for(b in this._http_headers)YAHOO.lang.hasOwnProperty(this._http_headers,b)&&a.conn.setRequestHeader(b,this._http_headers[b]);delete this._http_headers;this._http_headers={};this._has_http_headers=!1}},resetDefaultHeaders:function(){delete this._default_headers;this._default_headers={};this._has_default_headers=
!1},setForm:function(a,b,c){var d,g=!1,f=[],e=0,h,k,l,n;this.resetFormState();if("string"==typeof a)a=document.getElementById(a)||document.forms[a];else if("object"!=typeof a)return;if(b)this.createFrame(c?c:null),this._isFileUpload=this._isFormSubmit=!0,this._formNode=a;else{h=0;for(k=a.elements.length;h<k;++h)if(b=a.elements[h],d=b.disabled,c=b.name,!d&&c)switch(c=encodeURIComponent(c)+"=",d=encodeURIComponent(b.value),b.type){case "select-one":-1<b.selectedIndex&&(n=b.options[b.selectedIndex],
f[e++]=c+encodeURIComponent(n.attributes.value&&n.attributes.value.specified?n.value:n.text));break;case "select-multiple":if(-1<b.selectedIndex)for(d=b.selectedIndex,l=b.options.length;d<l;++d)n=b.options[d],n.selected&&(f[e++]=c+encodeURIComponent(n.attributes.value&&n.attributes.value.specified?n.value:n.text));break;case "radio":case "checkbox":b.checked&&(f[e++]=c+d);break;case "file":case void 0:case "reset":case "button":break;case "submit":!1===g&&(this._hasSubmitListener&&this._submitElementValue?
f[e++]=this._submitElementValue:f[e++]=c+d,g=!0);break;default:f[e++]=c+d}this._isFormSubmit=!0;this._sFormData=f.join("&");this.initHeader("Content-Type",this._default_form_header);return this._sFormData}},resetFormState:function(){this._isFileUpload=this._isFormSubmit=!1;this._formNode=null;this._sFormData=""},createFrame:function(a){var b="yuiIO"+this._transaction_id,c;YAHOO.env.ua.ie?(c=document.createElement('<iframe id="'+b+'" name="'+b+'" />'),"boolean"==typeof a&&(c.src="javascript:false")):
(c=document.createElement("iframe"),c.id=b,c.name=b);c.style.position="absolute";c.style.top="-1000px";c.style.left="-1000px";document.body.appendChild(c)},appendPostData:function(a){var b=[];a=a.split("&");var c,d;for(c=0;c<a.length;c++)d=a[c].indexOf("="),-1!=d&&(b[c]=document.createElement("input"),b[c].type="hidden",b[c].name=decodeURIComponent(a[c].substring(0,d)),b[c].value=decodeURIComponent(a[c].substring(d+1)),this._formNode.appendChild(b[c]));return b},uploadFile:function(a,b,c,d){var g=
"yuiIO"+a.tId,f=document.getElementById(g),e=this,h=b&&b.argument?b.argument:null,k,l,n,p={action:this._formNode.getAttribute("action"),method:this._formNode.getAttribute("method"),target:this._formNode.getAttribute("target")};this._formNode.setAttribute("action",c);this._formNode.setAttribute("method","POST");this._formNode.setAttribute("target",g);YAHOO.env.ua.ie?this._formNode.setAttribute("encoding","multipart/form-data"):this._formNode.setAttribute("enctype","multipart/form-data");d&&(k=this.appendPostData(d));
this._formNode.submit();this.startEvent.fire(a,h);a.startEvent&&a.startEvent.fire(a,h);b&&b.timeout&&(this._timeOut[a.tId]=window.setTimeout(function(){e.abort(a,b,!0)},b.timeout));if(k&&0<k.length)for(c=0;c<k.length;c++)this._formNode.removeChild(k[c]);for(l in p)YAHOO.lang.hasOwnProperty(p,l)&&(p[l]?this._formNode.setAttribute(l,p[l]):this._formNode.removeAttribute(l));this.resetFormState();var m=function(){b&&b.timeout&&(window.clearTimeout(e._timeOut[a.tId]),delete e._timeOut[a.tId]);e.completeEvent.fire(a,
h);a.completeEvent&&a.completeEvent.fire(a,h);n={tId:a.tId,argument:b.argument};try{n.responseText=f.contentWindow.document.body?f.contentWindow.document.body.innerHTML:f.contentWindow.document.documentElement.textContent,n.responseXML=f.contentWindow.document.XMLDocument?f.contentWindow.document.XMLDocument:f.contentWindow.document}catch(c){}b&&b.upload&&(b.scope?b.upload.apply(b.scope,[n]):b.upload(n));e.uploadEvent.fire(n);a.uploadEvent&&a.uploadEvent.fire(n);YAHOO.util.Event.removeListener(f,
"load",m);setTimeout(function(){document.body.removeChild(f);e.releaseObject(a)},100)};YAHOO.util.Event.addListener(f,"load",m)},abort:function(a,b,c){var d,g=b&&b.argument?b.argument:null;if(a&&a.conn)this.isCallInProgress(a)&&(a.conn.abort(),window.clearInterval(this._poll[a.tId]),delete this._poll[a.tId],c&&(window.clearTimeout(this._timeOut[a.tId]),delete this._timeOut[a.tId]),d=!0);else if(a&&!0===a.isUpload){var f=document.getElementById("yuiIO"+a.tId);f&&(YAHOO.util.Event.removeListener(f,
"load"),document.body.removeChild(f),c&&(window.clearTimeout(this._timeOut[a.tId]),delete this._timeOut[a.tId]),d=!0)}else d=!1;!0===d&&(this.abortEvent.fire(a,g),a.abortEvent&&a.abortEvent.fire(a,g),this.handleTransactionResponse(a,b,!0));return d},isCallInProgress:function(a){return a&&a.conn?4!==a.conn.readyState&&0!==a.conn.readyState:a&&!0===a.isUpload?document.getElementById("yuiIO"+a.tId)?!0:!1:!1},releaseObject:function(a){a&&a.conn&&(a.conn=null)}};
YAHOO.register("connection",YAHOO.util.Connect,{version:"2.6.0",build:"1321"});if(!window.console||!console.firebug){window.console={};for(var names="log debug info warn error assert dir dirxml group groupEnd time timeEnd count trace profile profileEnd".split(" "),i=0;i<names.length;++i)window.console[names[i]]=function(){}}
var SESSIONURL="undefined"==typeof SESSIONURL?"":SESSIONURL,SECURITYTOKEN="undefined"==typeof SECURITYTOKEN?"":SECURITYTOKEN,vbphrase="undefined"==typeof vbphrase?[]:vbphrase,vB_Editor=[],ignorequotechars=!1,pagenavcounter=0,is_regexp=window.RegExp?!0:!1,AJAX_Compatible=!1,viewport_info=null,vB_Default_Timeout=15E3,userAgent=navigator.userAgent.toLowerCase(),is_opera=-1!=userAgent.indexOf("opera")||"undefined"!=typeof window.opera,is_saf=-1!=userAgent.indexOf("applewebkit")||"Apple Computer, Inc."==
navigator.vendor,is_webtv=-1!=userAgent.indexOf("webtv"),is_ie=-1!=userAgent.indexOf("msie")&&!is_opera&&!is_saf&&!is_webtv,is_ie4=is_ie&&-1!=userAgent.indexOf("msie 4."),is_ie7=is_ie&&-1!=userAgent.indexOf("msie 7."),is_ps3=-1!=userAgent.indexOf("playstation 3"),is_moz="Gecko"==navigator.product&&!is_saf,is_kon=-1!=userAgent.indexOf("konqueror"),is_ns=-1==userAgent.indexOf("compatible")&&-1!=userAgent.indexOf("mozilla")&&!is_opera&&!is_webtv&&!is_saf,is_ns4=is_ns&&4==parseInt(navigator.appVersion),
is_mac=-1!=userAgent.indexOf("mac"),pointer_cursor=is_ie?"hand":"pointer";String.prototype.vBlength=function(){return is_ie&&-1!=this.indexOf("\n")?this.replace(/\r?\n/g,"_").length:this.length};"12"=="1234".substr(-2,2)&&(String.prototype.substr_orig=String.prototype.substr,String.prototype.substr=function(a,b){return"undefined"==typeof b?this.substr_orig(0>a?this.length+a:a):this.substr_orig(0>a?this.length+a:a,b)});
"undefined"===typeof Array.prototype.shift&&(Array.prototype.shift=function(){for(var a=0,b=this[0],c=this.length-1;a<c;a++)this[a]=this[a+1];this.length--;return b});function fetch_object(a){return document.getElementById?document.getElementById(a):document.all?document.all[a]:document.layers?document.layers[a]:null}function fetch_tags(a,b){return null==a?[]:"undefined"!=typeof a.getElementsByTagName?a.getElementsByTagName(b):a.all&&a.all.tags?a.all.tags(b):[]}
function fetch_tag_count(a,b){return fetch_tags(a,b).length}function do_an_e(a){if(!a||is_ie)return window.event.returnValue=!1,window.event.cancelBubble=!0,window.event;a.stopPropagation();a.preventDefault();return a}function e_by_gum(a){if(!a||is_ie)return window.event.cancelBubble=!0,window.event;"submit"==a.target.type&&a.target.form.submit();a.stopPropagation();return a}
function validatemessage(a,b,c){return is_kon||is_saf||is_webtv?!0:1>b.length?(alert(vbphrase.must_enter_subject),!1):PHP.trim(stripcode(a,!1,ignorequotechars)).length<c?(alert(construct_phrase(vbphrase.message_too_short,c)),!1):"undefined"!=typeof document.forms.vbform&&"undefined"!=typeof document.forms.vbform.imagestamp&&(document.forms.vbform.imagestamp.failed=!1,6!=document.forms.vbform.imagestamp.value.length)?(alert(vbphrase.complete_image_verification),document.forms.vbform.imagestamp.failed=
!0,document.forms.vbform.imagestamp.focus(),!1):!0}
function stripcode(a,b,c){if(!is_regexp)return a;if(c)for(c=(new Date).getTime();!1!==(startindex=PHP.stripos(a,"[quote"))&&!(2E3<(new Date).getTime()-c);){if(!1!==(stopindex=PHP.stripos(a,"[/quote]")))fragment=a.substr(startindex,stopindex-startindex+8),a=a.replace(fragment,"");else break;a=PHP.trim(a)}b?(a=a.replace(/<img[^>]+src="([^"]+)"[^>]*>/gi,"$1"),b=RegExp("<\\/\\w+>","gi"),a=a.replace(RegExp("<(\\w+)[^>]*>","gi"),""),a=a.replace(b,""),a=a.replace(RegExp("(&nbsp;)","gi")," ")):(b=RegExp("\\[\\/(\\w+)\\]",
"gi"),a=a.replace(RegExp("\\[(\\w+)(=[^\\]]*)?\\]","gi"),""),a=a.replace(b,""));return a}function vB_PHP_Emulator(){}vB_PHP_Emulator.prototype.stripos=function(a,b,c){"undefined"==typeof c&&(c=0);index=a.toLowerCase().indexOf(b.toLowerCase(),c);return-1==index?!1:index};vB_PHP_Emulator.prototype.ltrim=function(a){return a.replace(/^\s+/g,"")};vB_PHP_Emulator.prototype.rtrim=function(a){return a.replace(/(\s+)$/g,"")};vB_PHP_Emulator.prototype.trim=function(a){return this.ltrim(this.rtrim(a))};
vB_PHP_Emulator.prototype.preg_quote=function(a){return a.replace(/(\+|\{|\}|\(|\)|\[|\]|\||\/|\?|\^|\$|\\|\.|\=|\!|\<|\>|\:|\*)/g,"\\$1")};vB_PHP_Emulator.prototype.match_all=function(a,b){var c=a.match(RegExp(b,"gim"));if(c){for(var d=[],g=RegExp(b,"im"),f=0;f<c.length;f++)d[d.length]=c[f].match(g);return d}return!1};
vB_PHP_Emulator.prototype.unhtmlspecialchars=function(a){var b=[/&lt;/g,/&gt;/g,/&quot;/g,/&amp;/g],c=["<",">",'"',"&"],d;for(d in b)YAHOO.lang.hasOwnProperty(b,d)&&(a=a.replace(b[d],c[d]));return a};vB_PHP_Emulator.prototype.unescape_cdata=function(a){return a.replace(/<\=\!\=\[\=C\=D\=A\=T\=A\=\[/g,"<![CDATA[").replace(/\]\=\]\=>/g,"]]\x3e")};
vB_PHP_Emulator.prototype.htmlspecialchars=function(a){for(var b=[is_mac&&is_ie?RegExp("&","g"):RegExp("&(?!#[0-9]+;)","g"),RegExp("<","g"),RegExp(">","g"),RegExp('"',"g")],c=["&amp;","&lt;","&gt;","&quot;"],d=0;d<b.length;d++)a=a.replace(b[d],c[d]);return a};
vB_PHP_Emulator.prototype.in_array=function(a,b,c){a=new String(a);var d;if(c)for(d in a=a.toLowerCase(),b){if(YAHOO.lang.hasOwnProperty(b,d)&&b[d].toLowerCase()==a)return d}else for(d in b)if(YAHOO.lang.hasOwnProperty(b,d)&&b[d]==a)return d;return-1};vB_PHP_Emulator.prototype.str_pad=function(a,b,c){a=new String(a);c=new String(c);if(a.length<b){for(padtext=new String(c);padtext.length<b-a.length;)padtext+=c;a=padtext.substr(0,b-a.length)+a}return a};
vB_PHP_Emulator.prototype.urlencode=function(a){a=escape(a.toString()).replace(/\+/g,"%2B");var b=a.match(/(%([0-9A-F]{2}))/gi);if(b)for(var c=0;c<b.length;c++){var d=b[c].substring(1,3);128<=parseInt(d,16)&&(a=a.replace(b[c],"%u00"+d))}return a=a.replace("%25","%u0025")};vB_PHP_Emulator.prototype.ucfirst=function(a,b){if("undefined"!=typeof b){var c=a.indexOf(b);0<c&&(a=a.substr(0,c))}a=a.split(" ");for(c=0;c<a.length;c++)a[c]=a[c].substr(0,1).toUpperCase()+a[c].substr(1);return a.join(" ")};
function vB_AJAX_Handler(a){this.async=a?!0:!1;this.conn=null}vB_AJAX_Handler.prototype.init=function(){return AJAX_Compatible};vB_AJAX_Handler.is_compatible=function(){return AJAX_Compatible};vB_AJAX_Handler.prototype.onreadystatechange=function(a){this.callback=a};
vB_AJAX_Handler.prototype.fetch_data=function(a){console.warn('vB_AJAX_Handler.prototype.fetch_data() is deprecated.\nUse responseXML.getElementsByTagName("x")[i].firstChild.nodeValue instead.');return a&&a.firstChild&&a.firstChild.nodeValue?PHP.unescape_cdata(a.firstChild.nodeValue):""};vB_AJAX_Handler.prototype.send=function(a,b){this.conn=YAHOO.util.Connect.asyncRequest("POST",a,{success:this.callback},b+"&securitytoken="+SECURITYTOKEN+"&s="+fetch_sessionhash());this.handler=this.conn.conn};
function is_ajax_compatible(){if("undefined"!=typeof vb_disable_ajax&&2==vb_disable_ajax)return!1;if(is_ie&&!is_ie4)return!0;if(window.XMLHttpRequest)try{return(new XMLHttpRequest).setRequestHeader?!0:!1}catch(a){return!1}else return!1}AJAX_Compatible=is_ajax_compatible();console.info("This browser is%s AJAX compatible",AJAX_Compatible?"":" NOT");function vBulletin_AJAX_Error_Handler(a){console.warn("AJAX Error: Status = %s: %s",a.status,a.statusText)}
function vB_Hidden_Form(a){this.action=a;this.variables=[]}vB_Hidden_Form.prototype.add_variable=function(a,b){this.variables[this.variables.length]=[a,b];console.log("vB_Hidden_Form :: add_variable(%s)",a)};
vB_Hidden_Form.prototype.add_variables_from_object=function(a){if(a){console.info("vB_Hidden_Form :: add_variables_from_object(%s)",a.id);var b=fetch_tags(a,"input"),c;for(c=0;c<b.length;c++)switch(b[c].type){case "checkbox":case "radio":b[c].checked&&this.add_variable(b[c].name,b[c].value);break;case "text":case "hidden":case "password":this.add_variable(b[c].name,b[c].value)}b=fetch_tags(a,"textarea");for(c=0;c<b.length;c++)this.add_variable(b[c].name,b[c].value);a=fetch_tags(a,"select");for(c=
0;c<a.length;c++)if(a[c].multiple)for(b=0;b<a[c].options.length;b++)a[c].options[b].selected&&this.add_variable(a[c].name,a[c].options[b].value);else this.add_variable(a[c].name,a[c].options[a[c].selectedIndex].value)}};vB_Hidden_Form.prototype.fetch_variable=function(a){for(var b=0;b<this.variables.length;b++)if(this.variables[b][0]==a)return this.variables[b][1];return null};
vB_Hidden_Form.prototype.submit_form=function(){this.form=document.createElement("form");this.form.method="post";this.form.action=this.action;for(var a=0;a<this.variables.length;a++){var b=document.createElement("input");b.type="hidden";b.name=this.variables[a][0];b.value=this.variables[a][1];this.form.appendChild(b)}console.info("vB_Hidden_Form :: submit_form() -> %s",this.action);document.body.appendChild(this.form).submit()};
vB_Hidden_Form.prototype.build_query_string=function(){for(var a="",b=0;b<this.variables.length;b++)a+=this.variables[b][0]+"="+PHP.urlencode(this.variables[b][1])+"&";console.info("vB_Hidden_Form :: Query String = %s",a);return a};vB_Hidden_Form.prototype.add_input=vB_Hidden_Form.prototype.add_variable;vB_Hidden_Form.prototype.add_inputs_from_object=vB_Hidden_Form.prototype.add_variables_from_object;
function vB_Select_Overlay_Handler(a){if(this.browser_affected=is_ie&&!is_ie7)this.overlay=YAHOO.util.Dom.get(a),this.hidden_selects=[],console.log("Initializing <select> overlay handler for '%s'.",this.overlay.id)}
vB_Select_Overlay_Handler.prototype.hide=function(){if(this.browser_affected)for(var a=YAHOO.util.Dom.getRegion(this.overlay),b=document.getElementsByTagName("select"),c=0;c<b.length;c++)region_intersects(b[c],a)&&!YAHOO.util.Dom.isAncestor(this.overlay,b[c])&&(YAHOO.util.Dom.setStyle(b[c],"visibility","hidden"),this.hidden_selects.push(YAHOO.util.Dom.generateId(b[c])))};
vB_Select_Overlay_Handler.prototype.show=function(){if(this.browser_affected)for(var a;a=this.hidden_selects.pop();)YAHOO.util.Dom.setStyle(a,"visibility","visible")};function openWindow(a,b,c,d){return window.open(a,"undefined"==typeof d?"vBPopup":d,"statusbar=no,menubar=no,toolbar=no,scrollbars=yes,resizable=yes"+("undefined"!=typeof b?",width="+b:"")+("undefined"!=typeof c?",height="+c:""))}
function js_open_help(a,b,c){return openWindow("help.php?s="+SESSIONHASH+"&do=answer&page="+a+"&pageaction="+b+"&option="+c,600,450,"helpwindow")}function attachments(a){return openWindow("misc.php?"+SESSIONURL+"do=showattachments&t="+a,480,300)}function who(a){return openWindow("misc.php?"+SESSIONURL+"do=whoposted&t="+a,230,300)}function imwindow(a,b,c,d){return openWindow("sendmessage.php?"+SESSIONURL+"do=im&type="+a+"&u="+b,c,d)}
function SendMSNMessage(a){if(is_ie)try{MsgrObj.InstantMessage(a)}catch(b){alert(vbphrase.msn_functions_only_work_in_ie)}else alert(vbphrase.msn_functions_only_work_in_ie);return!1}function AddMSNContact(a){if(is_ie)try{MsgrObj.AddContact(0,a)}catch(b){alert(vbphrase.msn_functions_only_work_in_ie)}else alert(vbphrase.msn_functions_only_work_in_ie);return!1}
function detect_caps_lock(a){a=a?a:window.event;var b=a.which?a.which:a.keyCode?a.keyCode:a.charCode?a.charCode:0,c=a.shiftKey||a.modifiers&&a.modifiers&4;a=a.ctrlKey||a.modifiers&&a.modifiers&2;return 65<=b&&90>=b&&!c&&!a||97<=b&&122>=b&&c}function log_out(a){var b=document.getElementsByTagName("html")[0];b.style.filter="progid:DXImageTransform.Microsoft.BasicImage(grayscale=1)";if(confirm(a))return!0;b.style.filter="";return!1}
function set_cookie(a,b,c){console.log("Set Cookie :: %s = '%s'",a,b);document.cookie=a+"="+escape(b)+"; path=/"+("undefined"!=typeof c?"; expires="+c.toGMTString():"")}function delete_cookie(a){console.log("Delete Cookie :: %s",a);document.cookie=a+"=; expires=Thu, 01-Jan-70 00:00:01 GMT; path=/"}
function fetch_cookie(a){cookie_name=a+"=";cookie_length=document.cookie.length;for(cookie_begin=0;cookie_begin<cookie_length;){value_begin=cookie_begin+cookie_name.length;if(document.cookie.substring(cookie_begin,value_begin)==cookie_name){var b=document.cookie.indexOf(";",value_begin);-1==b&&(b=cookie_length);b=unescape(document.cookie.substring(value_begin,b));console.log("Fetch Cookie :: %s = '%s'",a,b);return b}cookie_begin=document.cookie.indexOf(" ",cookie_begin)+1;if(0==cookie_begin)break}console.log("Fetch Cookie :: %s (null)",
a);return null}function js_toggle_all(a,b,c,d,g){for(var f=0;f<a.elements.length;f++){var e=a.elements[f];if(e.type==b&&-1==PHP.in_array(e.name,d,!1))switch(b){case "radio":e.value==c&&(e.checked=g);break;case "select-one":e.selectedIndex=g;break;default:e.checked=g}}}function js_select_all(a){exclude=["selectall"];js_toggle_all(a,"select-one","",exclude,a.selectall.selectedIndex)}
function js_check_all(a){exclude=["keepattachments","allbox","removeall"];js_toggle_all(a,"checkbox","",exclude,a.allbox.checked)}function js_check_all_option(a,b){exclude=["useusergroup"];js_toggle_all(a,"radio",b,exclude,!0)}function checkall(a){js_check_all(a)}function checkall_option(a,b){js_check_all_option(a,b)}function resize_textarea(a,b){var c=fetch_object(b);c.style.width=parseInt(c.offsetWidth)+(0>a?-100:100)+"px";c.style.height=parseInt(c.offsetHeight)+(0>a?-100:100)+"px";return!1}
function region_intersects(a,b){a="undefined"==typeof a.left?YAHOO.util.Dom.getRegion(a):a;b="undefined"==typeof b.left?YAHOO.util.Dom.getRegion(b):b;return a.left>b.right||a.right<b.left||a.top>b.bottom||a.bottom<b.top?!1:!0}
function fetch_viewport_info(){null==viewport_info&&(viewport_info={x:YAHOO.util.Dom.getDocumentScrollLeft(),y:YAHOO.util.Dom.getDocumentScrollTop(),w:YAHOO.util.Dom.getViewportWidth(),h:YAHOO.util.Dom.getViewportHeight()},console.info("Viewport Info: Size = %dx%d, Position = %d,%d",viewport_info.w,viewport_info.h,viewport_info.x,viewport_info.y));return viewport_info}function clear_viewport_info(){viewport_info=null}
function center_element(a){viewport_info=fetch_viewport_info();YAHOO.util.Dom.setXY(a,[viewport_info.w/2+viewport_info.x-a.clientWidth/2,viewport_info.h/2+viewport_info.y-a.clientHeight/2])}
function fetch_all_stylesheets(a){a=[];for(var b=0,c=null,d=0,g=0,b=0;b<document.styleSheets.length;b++){c=document.styleSheets[b];a.push(c);try{if(c.cssRules)for(d=0;d<c.cssRules.length;d++)c.cssRules[d].styleSheet&&a.push(c.cssRules[d].styleSheet);else if(c.imports)for(g=0;g<c.imports.length;g++)a.push(c.imports[g])}catch(f){a.pop()}}return a}
function highlight_login_box(){var a=fetch_object("navbar_username"),b;if(a)for(a.focus(),a.select(),b=0;1600>b;b+=400)window.setTimeout(function(){YAHOO.util.Dom.addClass(a,"inlinemod")},b),window.setTimeout(function(){YAHOO.util.Dom.removeClass(a,"inlinemod")},b+200);return!1}
function toggle_collapse(a){if(!is_regexp)return!1;var b=fetch_object("collapseobj_"+a),c=fetch_object("collapseimg_"+a),d=fetch_object("collapsecel_"+a);if(!b)return c&&(c.style.display="none"),!1;"none"==b.style.display?(b.style.display="",save_collapsed(a,!1),c&&(img_re=/_collapsed\.gif$/,c.src=c.src.replace(img_re,".gif")),d&&(cel_re=/^(thead|tcat)(_collapsed)$/,d.className=d.className.replace(cel_re,"$1"))):(b.style.display="none",save_collapsed(a,!0),c&&(img_re=/\.gif$/,c.src=c.src.replace(img_re,
"_collapsed.gif")),d&&(cel_re=/^(thead|tcat)$/,d.className=d.className.replace(cel_re,"$1_collapsed")));return!1}function save_collapsed(a,b){var c=fetch_cookie("vbulletin_collapse"),d=[];if(null!=c){var c=c.split("\n"),g;for(g in c)YAHOO.lang.hasOwnProperty(c,g)&&(c[g]!=a&&""!=c[g])&&(d[d.length]=c[g])}b&&(d[d.length]=a);expires=new Date;expires.setTime(expires.getTime()+31536E6);set_cookie("vbulletin_collapse",d.join("\n"),expires)}function vBpagenav(){}
vBpagenav.prototype.controlobj_onclick=function(a){this._onclick(a);a=fetch_tags(this.menu.menuobj,"input");for(var b=0;b<a.length;b++)if("text"==a[b].type){a[b].focus();break}};vBpagenav.prototype.form_gotopage=function(a){0<(pagenum=parseInt(fetch_object("pagenav_itxt").value,10))&&(window.location=vBmenu.menus[vBmenu.activemenu].addr+"&page="+pagenum);return!1};vBpagenav.prototype.ibtn_onclick=function(a){return this.form.gotopage()};
vBpagenav.prototype.itxt_onkeypress=function(a){return 13==(a?a:window.event).keyCode?this.form.gotopage():!0};function vbmenu_register(a,b,c){return"object"==typeof vBmenu?vBmenu.register(a,b):!1}function string_to_node(a){var b=document.createElement("div");b.innerHTML=a;for(a=b.firstChild;a&&1!=a.nodeType;)a=a.nextSibling;return a?a.cloneNode(!0):b.firstChild.cloneNode(!0)}
function set_unselectable(a){a=YAHOO.util.Dom.get(a);if(!is_ie4&&"undefined"!=typeof a.tagName){if(a.hasChildNodes())for(var b=0;b<a.childNodes.length;b++)set_unselectable(a.childNodes[b]);a.unselectable="on"}}function fetch_sessionhash(){return""==SESSIONURL?"":SESSIONURL.substr(2,32)}function construct_phrase(){if(!arguments||1>arguments.length||!is_regexp)return!1;for(var a=arguments,b=a[0],c,d=1;d<a.length;d++)c=RegExp("%"+d+"\\$s","gi"),b=b.replace(c,a[d]);return b}
function switch_id(a,b){var c=a.options[a.selectedIndex].value;if(""!=c){var d=new String(window.location),g=new String(""),d=d.split("#");d[1]&&(g="#"+d[1]);d=d[0];-1!=d.indexOf(b+"id=")&&is_regexp&&(d=d.replace(RegExp(b+"id=\\d+&?"),""));-1==d.indexOf("?")?d+="?":(lastchar=d.substr(d.length-1),"&"!=lastchar&&"?"!=lastchar&&(d+="&"));window.location=d+b+"id="+c+g}}function child_img_alt_2_title(a){a=a.getElementsByTagName("img");for(var b=0;b<a.length;b++)img_alt_2_title(a[b])}
function img_alt_2_title(a){a.title||""==a.alt||(a.title=a.alt)}function do_securitytoken_replacement(a){if(""!=a){for(var b=0;b<document.forms.length;b++)document.forms[b].elements.securitytoken&&document.forms[b].elements.securitytoken.value==SECURITYTOKEN&&(document.forms[b].elements.securitytoken.value=a);SECURITYTOKEN=a;console.log("Securitytoken updated")}}
function handle_securitytoken_response(a){console.log("Processing securitytoken update");a.responseXML&&a.responseXML.getElementsByTagName("securitytoken").length?(a=a.responseXML.getElementsByTagName("securitytoken")[0].firstChild.nodeValue,do_securitytoken_replacement(a),securitytoken_errors=0):handle_securitytoken_error(a)}function handle_securitytoken_error(a){console.log("Securitytoken Error");3==++securitytoken_errors&&do_securitytoken_replacement("guest")}
var securitytoken_timeout=window.setTimeout("replace_securitytoken()",36E5),securitytoken_errors=0;
function replace_securitytoken(){window.clearTimeout(securitytoken_timeout);AJAX_Compatible&&(""!=SECURITYTOKEN&&"guest"!=SECURITYTOKEN)&&(securitytoken_timeout=window.setTimeout("replace_securitytoken()",36E5),YAHOO.util.Connect.asyncRequest("POST","ajax.php",{success:handle_securitytoken_response,failure:handle_securitytoken_error,timeout:vB_Default_Timeout},SESSIONURL+"securitytoken="+SECURITYTOKEN+"&do=securitytoken"))}
function Comment_Init(a){if("undefined"!=typeof a.id){var b=a.id;if(isNaN(b)){var c=null;if(c=b.match(/(\d+)/))b=c[0]}"undefined"!=typeof inlineMod_comment&&im_init(a,inlineMod_comment);"undefined"!=typeof vB_QuickEditor_Factory&&("undefined"==typeof vB_QuickEditor_Factory.controls[b]?vB_QuickEditor_Factory.controls[b]=new vB_QuickEditor(b,vB_QuickEditor_Factory):vB_QuickEditor_Factory.controls[b].init());"undefined"!=typeof vB_QuickLoader_Factory&&(vB_QuickLoader_Factory.controls[b]=new vB_QuickLoader(b,
vB_QuickLoader_Factory));child_img_alt_2_title(a)}}
function PostBit_Init(a,b){console.log("PostBit Init: %d",b);if("undefined"!=typeof vBmenu)for(var c=fetch_tags(a,"div"),d=0;d<c.length;d++)c[d].id&&"postmenu_"==c[d].id.substr(0,9)&&vBmenu.register(c[d].id,!0);"undefined"!=typeof vB_QuickEditor&&vB_AJAX_QuickEdit_Init(a);"undefined"!=typeof vB_QuickReply&&qr_init_buttons(a);"undefined"!=typeof mq_init&&mq_init(a);"undefined"!=typeof vBrep&&"undefined"!=typeof b&&"null"!=typeof b&&vbrep_register(b);"undefined"!=typeof inlineMod&&im_init(a);"undefined"!=
typeof vB_Lightbox&&init_postbit_lightbox(a);child_img_alt_2_title(a)}
function vBulletin_init(){if(is_webtv)return!1;child_img_alt_2_title(document);if("object"==typeof vBmenu){"undefined"!=typeof YAHOO?(YAHOO.util.Event.on(document,"click",vbmenu_hide),YAHOO.util.Event.on(window,"resize",vbmenu_hide)):window.attachEvent&&!is_saf?(document.attachEvent("onclick",vbmenu_hide),window.attachEvent("onresize",vbmenu_hide)):document.addEventListener&&!is_saf?(document.addEventListener("click",vbmenu_hide,!1),window.addEventListener("resize",vbmenu_hide,!1)):(window.onclick=
vbmenu_hide,window.onresize=vbmenu_hide);for(var a=fetch_tags(document,"td"),b=0;b<a.length;b++)if(a[b].hasChildNodes()&&a[b].firstChild.name&&-1!=a[b].firstChild.name.indexOf("PageNav")){var c=a[b].title;a[b].title="";a[b].innerHTML="";a[b].id="pagenav."+b;var d=vBmenu.register(a[b].id);d.addr=c;is_saf&&(d.controlobj._onclick=d.controlobj.onclick,d.controlobj.onclick=vBpagenav.prototype.controlobj_onclick)}"undefined"!=typeof c&&(fetch_object("pagenav_form").gotopage=vBpagenav.prototype.form_gotopage,
fetch_object("pagenav_ibtn").onclick=vBpagenav.prototype.ibtn_onclick,fetch_object("pagenav_itxt").onkeypress=vBpagenav.prototype.itxt_onkeypress);vBmenu.activate(!0)}vBulletin.init();return!0}function vBulletin_Framework(){this.elements=[];this.ajaxurls=[];this.events=[];this.time=new Date;this.add_event("systemInit")}vBulletin_Framework.prototype.init=function(){console.info("Firing System Init");this.events.systemInit.fire()};
vBulletin_Framework.prototype.extend=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.baseConstructor=b;a.superClass=b.prototype};vBulletin_Framework.prototype.register_control=function(a,b){for(var c=[],d=1;d<arguments.length;d++)c.push(arguments[d]);this.elements[a]||(console.info('Creating array vBulletin.elements["%s"]',a),this.elements[a]=[]);d=this.elements[a].push(c);console.log('vBulletin.elements["%s"][%d] = %s',a,d-1,c.join(", "))};
vBulletin_Framework.prototype.register_ajax_urls=function(a,b,c){a=a.split("?");a[1]=SESSIONURL+"securitytoken="+SECURITYTOKEN+"&ajax=1&"+a[1].replace(/\{(\d+)(:\w+)?\}/gi,"%$1$s");b=b.split("?");b[1]=SESSIONURL+"securitytoken="+SECURITYTOKEN+"&ajax=1&"+b[1].replace(/\{(\d+)(:\w+)?\}/gi,"%$1$s");console.log("Register AJAX URLs for %s",c);for(var d=0;d<c.length;d++)this.ajaxurls[c[d]]=[a,b]};vBulletin_Framework.prototype.add_event=function(a){this.events[a]=new YAHOO.util.CustomEvent(a)};
vBulletin_Framework.prototype.console=function(){if(window.console||console.firebug){for(var a=[],b=0;b<arguments.length;b++)a[a.length]=arguments[b];try{eval("console.log('"+a.join("','")+"');")}catch(c){}}};var PHP=new vB_PHP_Emulator,vBulletin=new vBulletin_Framework;vBulletin.events.systemInit.subscribe(function(){YAHOO.util.Event.on(window,"resize",clear_viewport_info);YAHOO.util.Event.on(window,"scroll",clear_viewport_info)});